check for dependencies before processing

diff --git a/clean-and-update-v3mod b/clean-and-update-v3mod
--- a/clean-and-update-v3mod
+++ b/clean-and-update-v3mod
@@ -161,7 +161,7 @@ then
 	then
 		echo "$nzb"
 		echo
-		echo "Show Not Following A Recognizable Season/Episode Naming Standard"
+		echo "Donwloaded Files Not Following A Recognizable Season/Episode Naming Scheme"
 		echo "Ex: s01e01, s01x02, 01x03, etc..."
 		name_failed
 		## Failure, We're Exiting
@@ -172,6 +172,7 @@ fi
 ###### Remove Junk Files
 
 nodisp="0"
+clean="1"
 for junk in $GARBAGE ;
 do
 	trash=$(cd "$fpath" ; ls *.$junk 2> /dev/null)
@@ -199,6 +200,29 @@ fi
 echo
 attempt="0"
 
+wake_dep ()
+{
+DEPENDENCIES="wakeonlan curl"
+deps_ok="YES"
+for dep in $DEPENDENCIES
+do
+	if ! which $dep &>/dev/null ;
+	then
+	echo "This Script Requires $dep To Run But It Is Not Installed"
+	deps_ok="NO"
+	fi
+done
+if [[ "$deps_ok" == "NO" ]];
+then
+	echo "Unmet Dependencies."
+	echo "Processing Aborted."
+	fail="1"
+else
+	return 0
+fi
+}
+
+
 while true ;
 do
 	attempt=$(( attempt + 1 ))
@@ -217,6 +241,7 @@ do
 	if [ "$result" = "1" ] ;
 	then
 		echo ">> XBMC Is Inactive"
+		wake_dep
 		echo "Waking XBMC [ MAC: $xbmc_mac ]"
 		wakeonlan $xbmc_mac > /dev/null 2>&1
 		echo "Sleeping 100 seconds. "
